@tool
extends Node
class_name PatrolPath

# ─────────────────────────────────────────────
# PATROL PATH — an ordered walk, authored in the level.
#
# Two consumers now. Individual AI still call get_next_point() and step along
# it on their own. A Squad on SquadObjective.PATROL walks it as a unit instead,
# keeping formation and its role assignments, so contact with a patrol reads as
# meeting a squad rather than bumping into four separate robots.
#
# `tag` is how a mission asks for this route without knowing the node path.
# ─────────────────────────────────────────────

@export var tag: StringName = &""
@export var points: Array[Node3D]
# Walk back down the route instead of teleporting the index to the start. Looks
# right for a dead-end corridor; leave off for a circuit.
@export var ping_pong: bool = false

# ── EDITOR PREVIEW ────────────────────────────
# The line between points can't be authored as real nodes the way the point
# markers are, because it depends on where every point currently is. So it's
# generated by this @tool script instead.
#
# THE IMPORTANT TRICK: the generated MeshInstance3D is added WITHOUT an owner.
# A node with no owner is not serialised, so this never gets written into your
# .tscn no matter how many times you save — you get the preview without the
# scene file quietly filling up with generated geometry.
#
# It's also top_level, so it ignores whatever transform this node sits under and
# vertices can just be world positions.
@export var show_preview: bool = true:
	set(value):
		show_preview = value
		_rebuild_preview()
@export var preview_color: Color = Color(0.98, 0.79, 0.28, 0.85)
# Arrowheads along each leg so direction of travel is readable.
@export var arrow_size: float = 0.45
@export var preview_height: float = 0.35

var _preview: MeshInstance3D
var _last_positions: PackedVector3Array

var patrol_indices := {}

func _ready() -> void:
	add_to_group("patrol_paths")
	if Engine.is_editor_hint():
		set_process(true)
		_rebuild_preview()
	else:
		# Running the game — no preview, and nothing to tick.
		set_process(false)
		_clear_preview()


# Editor only. Points are separate nodes that can be dragged independently, so
# there's no single transform notification to hook; polling a handful of
# positions once a frame in the editor is cheap and always correct.
func _process(_delta: float) -> void:
	if not Engine.is_editor_hint():
		return
	if _positions_changed():
		_rebuild_preview()


func _positions_changed() -> bool:
	var current := PackedVector3Array()
	for p in points:
		if p != null and is_instance_valid(p):
			current.append(p.global_position)
	if current.size() != _last_positions.size():
		_last_positions = current
		return true
	for i in current.size():
		if current[i].distance_squared_to(_last_positions[i]) > 0.0001:
			_last_positions = current
			return true
	return false


func _clear_preview() -> void:
	if _preview != null and is_instance_valid(_preview):
		_preview.queue_free()
	_preview = null


func _rebuild_preview() -> void:
	if not Engine.is_editor_hint():
		return
	_clear_preview()
	if not show_preview or points.size() < 2:
		return

	var valid: Array[Node3D] = []
	for p in points:
		if p != null and is_instance_valid(p):
			valid.append(p)
	if valid.size() < 2:
		return

	var mesh := ImmediateMesh.new()
	var material := StandardMaterial3D.new()
	material.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	material.vertex_color_use_as_albedo = true
	material.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	# Draw through terrain — you're usually looking at a route from above with
	# geometry in the way, and a hidden preview is a useless one.
	material.no_depth_test = true

	mesh.surface_begin(Mesh.PRIMITIVE_LINES, material)
	var lift := Vector3.UP * preview_height
	var legs := valid.size() if not ping_pong else valid.size() - 1

	for i in legs:
		var a: Vector3 = valid[i].global_position + lift
		var b: Vector3 = valid[(i + 1) % valid.size()].global_position + lift
		# The closing leg of a loop is dimmer, so you can tell a circuit from a
		# there-and-back at a glance.
		var col := preview_color
		if not ping_pong and i == valid.size() - 1:
			col.a *= 0.4
		_line(mesh, a, b, col)
		_arrow(mesh, a, b, col)

	mesh.surface_end()

	_preview = MeshInstance3D.new()
	_preview.mesh = mesh
	_preview.top_level = true
	_preview.transform = Transform3D.IDENTITY
	_preview.name = "RoutePreview"
	# No owner = never written into the .tscn.
	add_child(_preview)

	# Number the markers so the order is readable in the viewport.
	for i in valid.size():
		if valid[i] is PatrolPoint:
			(valid[i] as PatrolPoint).display_index = i


func _line(mesh: ImmediateMesh, a: Vector3, b: Vector3, col: Color) -> void:
	mesh.surface_set_color(col)
	mesh.surface_add_vertex(a)
	mesh.surface_set_color(col)
	mesh.surface_add_vertex(b)


# A chevron at the midpoint of the leg, lying flat.
func _arrow(mesh: ImmediateMesh, a: Vector3, b: Vector3, col: Color) -> void:
	var dir := b - a
	if dir.length_squared() < 0.001:
		return
	dir = dir.normalized()
	var side := dir.cross(Vector3.UP)
	if side.length_squared() < 0.001:
		side = dir.cross(Vector3.RIGHT)
	side = side.normalized() * arrow_size * 0.6
	var tip := a.lerp(b, 0.5)
	var back := tip - dir * arrow_size
	_line(mesh, tip, back + side, col)
	_line(mesh, tip, back - side, col)


func point_at(index: int) -> Node3D:
	if points.is_empty():
		return null
	return points[clampi(index, 0, points.size() - 1)]


# Index stepping for a squad, which shares one index rather than one per AI.
func advance(index: int, forward: bool) -> Array:
	if points.size() <= 1:
		return [0, forward]
	if not ping_pong:
		return [(index + 1) % points.size(), true]
	var next := index + (1 if forward else -1)
	if next >= points.size():
		return [maxi(0, points.size() - 2), false]
	if next < 0:
		return [mini(1, points.size() - 1), true]
	return [next, forward]


func get_next_point(ai: Node) -> Node3D:
	if not ai in patrol_indices:
		patrol_indices[ai] = 0

	if points.is_empty():
		return null

	var index = patrol_indices[ai]
	var next_point = points[index]

	# Advance index for next time
	index = (index + 1) % points.size()
	patrol_indices[ai] = index
	return next_point
